### ISSUE TITLE
Расположение пинов в К140УД5А

### ISSUE THREAD

**Issue by mikhailnov** [ra3xdh/qucs-rus-complib#1]
Сейчас К140УД5 (k140ud5) выглядит вот так:
![image](https://user-images.githubusercontent.com/15802528/69916279-3ebec500-146a-11ea-95f3-1e65e24371e2.png)

Однако на доступных в интернете схемах предлагается подключить конденсатор к двум пинам рядом с минусом:
![image](https://user-images.githubusercontent.com/15802528/69916301-81809d00-146a-11ea-9dfb-d1c63856e9d7.png)
![image](https://user-images.githubusercontent.com/15802528/69916303-86dde780-146a-11ea-93d0-b7fbf2d6d3db.png)
![image](https://user-images.githubusercontent.com/15802528/69916307-8e9d8c00-146a-11ea-93c5-104215418514.png)
https://radiowiki.ru/wiki/К140УД5
https://cxem.net/beginner/beginner117.php

Я плохо разбираюсь в вопросе, это не ошибка в модели?

**Comment by ra3xdh** [comment]
Здравствуйте! Нет, это не ошибка. В библиотеках для всех ОУ выводы питания унифицированы: плюс вверху, минус внизу, чтобы можно обеспечить взаимозаменяемость ОУ в схемах и исключить ошибки Copy-Paste. Конденсатор в К140УД5 подключается к двум пинам вверху около плюсового вывода питания.

**Comment by mikhailnov** [comment]
Понятно, спасибо!
