### ISSUE TITLE
Укажите лицензию

### ISSUE THREAD

**Issue by antohami** [ra3xdh/qucs-rus-complib#2]
Укажите лицензию, чтобы можно было опакетить в репозиторий.

**Comment by ra3xdh** [comment]
Лицензию добавил этим коммитов https://github.com/ra3xdh/qucs-rus-complib/commit/b30585c0383fb927e4adeb8559bbcf7a83ca41a7

**Comment by ra3xdh** [comment]
Также при опакечивании следует учесть, что библиотеки `Tubes.lib` и `BF998.lib` я включил в дистрибутив основной программы (Qucs-S).
